name: /home/parikh92/.conda/envs/cent7/2024.02-py311/sciborg
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - comm=0.2.1=py311h06a4308_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - faiss-cpu=1.9.0=py3.11_hadc1362_0_cpu
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py311h06a4308_0
  - jedi=0.19.1=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libfaiss=1.9.0=hf65b397_0_cpu
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py311h06a4308_1
  - python=3.11.10=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - pyzmq=25.1.2=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.40.0
      - anyio==4.6.2.post1
      - anytree==2.13.0
      - ascii-colors==0.5.2
      - attrs==24.2.0
      - autograd==1.7.0
      - backcall==0.2.0
      - beartype==0.18.5
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - blockbuster==1.5.24
      - bs4==0.0.2
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - configparser==7.2.0
      - contourpy==1.3.1
      - cryptography==44.0.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - distro==1.9.0
      - docopt==0.6.2
      - fastjsonschema==2.21.1
      - fireworks-ai==0.15.12
      - fonttools==4.56.0
      - forbiddenfruit==0.1.4
      - frozenlist==1.5.0
      - future==1.0.0
      - gensim==4.3.3
      - graspologic==3.4.1
      - graspologic-native==1.2.5
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - httpx-ws==0.7.2
      - hyppo==0.4.0
      - idna==3.10
      - ipython==8.12.3
      - jinja2==3.1.6
      - jiter==0.8.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-rs==0.29.1
      - jsonschema-specifications==2025.4.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - langchain==0.3.8
      - langchain-anthropic==0.3.0
      - langchain-community==0.3.8
      - langchain-core==0.3.51
      - langchain-fireworks==0.2.9
      - langchain-openai==0.2.10
      - langchain-text-splitters==0.3.2
      - langgraph==0.2.59
      - langgraph-api==0.0.46
      - langgraph-checkpoint==2.0.24
      - langgraph-cli==0.1.89
      - langgraph-sdk==0.1.61
      - langsmith==0.1.147
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - marshmallow==3.23.1
      - matplotlib==3.10.0
      - mistune==3.1.3
      - msgpack==1.1.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nano-vectordb==0.0.4.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - numba==0.61.2
      - openai==1.55.1
      - orjson==3.10.12
      - ormsgpack==1.9.1
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - patsy==1.0.1
      - pdf2image==1.17.0
      - pdfminer-six==20231228
      - pdfplumber==0.11.5
      - pickleshare==0.7.5
      - pillow==11.1.0
      - pipmaster==0.5.4
      - pipreqs==0.5.0
      - pot==0.9.5
      - propcache==0.2.0
      - pycparser==2.22
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pydantic-settings==2.6.1
      - pyjwt==2.10.1
      - pymupdf==1.25.4
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pypdfium2==4.30.1
      - pytesseract==0.3.13
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - react-agent==0.0.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.12.0
      - seaborn==0.13.2
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.35
      - sse-starlette==2.1.3
      - starlette==0.46.1
      - statsmodels==0.14.4
      - structlog==25.2.0
      - tavily-python==0.5.4
      - tenacity==9.0.0
      - threadpoolctl==3.6.0
      - tiktoken==0.8.0
      - tinycss2==1.4.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - umap-learn==0.5.7
      - urllib3==2.2.3
      - uvicorn==0.34.0
      - watchfiles==1.0.4
      - webencodings==0.5.1
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xlsxwriter==3.2.2
      - yarg==0.1.9
      - yarl==1.18.0
prefix: /home/parikh92/.conda/envs/cent7/2024.02-py311/sciborg
